- hosts: 127.0.0.1
  connection: local
  become: root
  gather_facts: false
  serial: 1
  tasks:
    - name:  Create Onew Nodes
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        state: present
        folder: "{{ folder }}"
        template: "{{ template }}"
        name: Operator
        cluster: "{{ cluster }}"
        disk:
          - size_gb: 30
            type: thin
            datastore: datastore1
        hardware:
          memory_mb: 2048
          num_cpus: 2
          scsi: paravirtual
        networks:
          - name: VM Network
            ip: 10.10.5.130
            netmask: 255.255.255.0
            gateway: 10.10.5.254
        wait_for_ip_address: True
        customization:
          dns_servers:
            - 202.102.192.68
            - 114.114.114.114
      delegate_to: localhost